apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
          - amd64
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
          - ondemand
        - key: karpenter.k8s.io/instance-category
          operator: In
          values: ["t", "m"]
        - key: karpenter.k8s.io/instance-generation
          operator: Gt
          values:
          - "2"
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-west-1a
          - us-west-1c
      nodeClassRef:
        group: karpenter.sh
        kind: EC2NodeClass
        name: default
      expireAfter: 720h
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
